<!DOCTYPE HTML>
<html lang="en" class="sidebar-visible no-js light">
    <head>
        <!-- Book generated using mdBook -->
        <meta charset="UTF-8">
        <title>Des erreurs récupérables avec Result - Le langage de programmation Rust</title>
        
        


        <!-- Custom HTML head -->
        


        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#ffffff" />

        
        <link rel="icon" href="favicon.svg">
        
        
        <link rel="shortcut icon" href="favicon.png">
        
        <link rel="stylesheet" href="css/variables.css">
        <link rel="stylesheet" href="css/general.css">
        <link rel="stylesheet" href="css/chrome.css">
        
        <link rel="stylesheet" href="css/print.css" media="print">
        

        <!-- Fonts -->
        <link rel="stylesheet" href="FontAwesome/css/font-awesome.css">
        
        <link rel="stylesheet" href="fonts/fonts.css">
        

        <!-- Highlight.js Stylesheets -->
        <link rel="stylesheet" href="highlight.css">
        <link rel="stylesheet" href="tomorrow-night.css">
        <link rel="stylesheet" href="ayu-highlight.css">

        <!-- Custom theme stylesheets -->
        
        <link rel="stylesheet" href="../ferris.css">
        
        <link rel="stylesheet" href="../theme/2018-edition.css">
        

        
    </head>
    <body>
        <!-- Provide site root to javascript -->
        <script type="text/javascript">
            var path_to_root = "";
            var default_theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "navy" : "light";
        </script>

        <!-- Work around some values being stored in localStorage wrapped in quotes -->
        <script type="text/javascript">
            try {
                var theme = localStorage.getItem('mdbook-theme');
                var sidebar = localStorage.getItem('mdbook-sidebar');

                if (theme.startsWith('"') && theme.endsWith('"')) {
                    localStorage.setItem('mdbook-theme', theme.slice(1, theme.length - 1));
                }

                if (sidebar.startsWith('"') && sidebar.endsWith('"')) {
                    localStorage.setItem('mdbook-sidebar', sidebar.slice(1, sidebar.length - 1));
                }
            } catch (e) { }
        </script>

        <!-- Set the theme before any content is loaded, prevents flash -->
        <script type="text/javascript">
            var theme;
            try { theme = localStorage.getItem('mdbook-theme'); } catch(e) { }
            if (theme === null || theme === undefined) { theme = default_theme; }
            var html = document.querySelector('html');
            html.classList.remove('no-js')
            html.classList.remove('light')
            html.classList.add(theme);
            html.classList.add('js');
        </script>

        <!-- Hide / unhide sidebar before it is displayed -->
        <script type="text/javascript">
            var html = document.querySelector('html');
            var sidebar = 'hidden';
            if (document.body.clientWidth >= 1080) {
                try { sidebar = localStorage.getItem('mdbook-sidebar'); } catch(e) { }
                sidebar = sidebar || 'visible';
            }
            html.classList.remove('sidebar-visible');
            html.classList.add("sidebar-" + sidebar);
        </script>

        <nav id="sidebar" class="sidebar" aria-label="Table of contents">
            <div class="sidebar-scrollbox">
                <ol class="chapter"><li class="chapter-item expanded affix "><a href="title-page.html">Le langage de programmation Rust</a></li><li class="chapter-item expanded affix "><a href="foreword.html">Avant-propos</a></li><li class="chapter-item expanded affix "><a href="ch00-00-introduction.html">Introduction</a></li><li class="chapter-item expanded affix "><a href="translation-terms.html">Traduction des termes</a></li><li class="chapter-item expanded "><a href="ch01-00-getting-started.html"><strong aria-hidden="true">1.</strong> Prise en main</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch01-01-installation.html"><strong aria-hidden="true">1.1.</strong> Installation</a></li><li class="chapter-item expanded "><a href="ch01-02-hello-world.html"><strong aria-hidden="true">1.2.</strong> Hello, world!</a></li><li class="chapter-item expanded "><a href="ch01-03-hello-cargo.html"><strong aria-hidden="true">1.3.</strong> Hello, Cargo!</a></li></ol></li><li class="chapter-item expanded "><a href="ch02-00-guessing-game-tutorial.html"><strong aria-hidden="true">2.</strong> Programmer le jeu du plus ou du moins</a></li><li class="chapter-item expanded "><a href="ch03-00-common-programming-concepts.html"><strong aria-hidden="true">3.</strong> Les concepts courants de programmation</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch03-01-variables-and-mutability.html"><strong aria-hidden="true">3.1.</strong> Les variables et la mutabilité</a></li><li class="chapter-item expanded "><a href="ch03-02-data-types.html"><strong aria-hidden="true">3.2.</strong> Les types de données</a></li><li class="chapter-item expanded "><a href="ch03-03-how-functions-work.html"><strong aria-hidden="true">3.3.</strong> Les fonctions</a></li><li class="chapter-item expanded "><a href="ch03-04-comments.html"><strong aria-hidden="true">3.4.</strong> Les commentaires</a></li><li class="chapter-item expanded "><a href="ch03-05-control-flow.html"><strong aria-hidden="true">3.5.</strong> Les structures de contrôle</a></li></ol></li><li class="chapter-item expanded "><a href="ch04-00-understanding-ownership.html"><strong aria-hidden="true">4.</strong> Comprendre la possession</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch04-01-what-is-ownership.html"><strong aria-hidden="true">4.1.</strong> Qu'est-ce que la possession ?</a></li><li class="chapter-item expanded "><a href="ch04-02-references-and-borrowing.html"><strong aria-hidden="true">4.2.</strong> Les références et l'emprunt</a></li><li class="chapter-item expanded "><a href="ch04-03-slices.html"><strong aria-hidden="true">4.3.</strong> Le type slice</a></li></ol></li><li class="chapter-item expanded "><a href="ch05-00-structs.html"><strong aria-hidden="true">5.</strong> Utiliser les structures pour structurer des données apparentées</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch05-01-defining-structs.html"><strong aria-hidden="true">5.1.</strong> Définir et instancier des structures</a></li><li class="chapter-item expanded "><a href="ch05-02-example-structs.html"><strong aria-hidden="true">5.2.</strong> Un exemple de programme qui utilise des structures</a></li><li class="chapter-item expanded "><a href="ch05-03-method-syntax.html"><strong aria-hidden="true">5.3.</strong> La syntaxe des méthodes</a></li></ol></li><li class="chapter-item expanded "><a href="ch06-00-enums.html"><strong aria-hidden="true">6.</strong> Les énumérations et le filtrage par motif</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch06-01-defining-an-enum.html"><strong aria-hidden="true">6.1.</strong> Définir une énumération</a></li><li class="chapter-item expanded "><a href="ch06-02-match.html"><strong aria-hidden="true">6.2.</strong> La structure de contrôle match</a></li><li class="chapter-item expanded "><a href="ch06-03-if-let.html"><strong aria-hidden="true">6.3.</strong> Une structure de contrôle concise : if let</a></li></ol></li><li class="chapter-item expanded "><a href="ch07-00-managing-growing-projects-with-packages-crates-and-modules.html"><strong aria-hidden="true">7.</strong> Gérer des projets grandissants avec les paquets, crates et modules</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch07-01-packages-and-crates.html"><strong aria-hidden="true">7.1.</strong> Les paquets et les crates</a></li><li class="chapter-item expanded "><a href="ch07-02-defining-modules-to-control-scope-and-privacy.html"><strong aria-hidden="true">7.2.</strong> Définir des modules pour gérer la portée et la protection</a></li><li class="chapter-item expanded "><a href="ch07-03-paths-for-referring-to-an-item-in-the-module-tree.html"><strong aria-hidden="true">7.3.</strong> Désigner un élément dans l'arborescence de modules</a></li><li class="chapter-item expanded "><a href="ch07-04-bringing-paths-into-scope-with-the-use-keyword.html"><strong aria-hidden="true">7.4.</strong> Importer des chemins dans la portée via le mot-clé use</a></li><li class="chapter-item expanded "><a href="ch07-05-separating-modules-into-different-files.html"><strong aria-hidden="true">7.5.</strong> Séparer les modules dans différents fichiers</a></li></ol></li><li class="chapter-item expanded "><a href="ch08-00-common-collections.html"><strong aria-hidden="true">8.</strong> Les collections standard</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch08-01-vectors.html"><strong aria-hidden="true">8.1.</strong> Stocker des listes de valeurs avec des vecteurs</a></li><li class="chapter-item expanded "><a href="ch08-02-strings.html"><strong aria-hidden="true">8.2.</strong> Stocker du texte encodé en UTF-8 avec les Strings</a></li><li class="chapter-item expanded "><a href="ch08-03-hash-maps.html"><strong aria-hidden="true">8.3.</strong> Stocker des clés associées à des valeurs dans des tables de hachage</a></li></ol></li><li class="chapter-item expanded "><a href="ch09-00-error-handling.html"><strong aria-hidden="true">9.</strong> La gestion des erreurs</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch09-01-unrecoverable-errors-with-panic.html"><strong aria-hidden="true">9.1.</strong> Les erreurs irrécupérables avec panic!</a></li><li class="chapter-item expanded "><a href="ch09-02-recoverable-errors-with-result.html" class="active"><strong aria-hidden="true">9.2.</strong> Des erreurs récupérables avec Result</a></li><li class="chapter-item expanded "><a href="ch09-03-to-panic-or-not-to-panic.html"><strong aria-hidden="true">9.3.</strong> Paniquer ou ne pas paniquer, telle est la question ...</a></li></ol></li><li class="chapter-item expanded "><a href="ch10-00-generics.html"><strong aria-hidden="true">10.</strong> 🚧 Les types génériques, les traits et les durées de vies</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch10-01-syntax.html"><strong aria-hidden="true">10.1.</strong> 🚧 Les types de données génériques</a></li><li class="chapter-item expanded "><a href="ch10-02-traits.html"><strong aria-hidden="true">10.2.</strong> 🚧 Définir des comportements partagés avec les traits</a></li><li class="chapter-item expanded "><a href="ch10-03-lifetime-syntax.html"><strong aria-hidden="true">10.3.</strong> 🚧 La conformité des références avec les durées de vies</a></li></ol></li><li class="chapter-item expanded "><a href="ch11-00-testing.html"><strong aria-hidden="true">11.</strong> 🚧 Ecrire des tests automatisés</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch11-01-writing-tests.html"><strong aria-hidden="true">11.1.</strong> 🚧 Comment écrire des tests</a></li><li class="chapter-item expanded "><a href="ch11-02-running-tests.html"><strong aria-hidden="true">11.2.</strong> 🚧 Gérer l'exécution des tests</a></li><li class="chapter-item expanded "><a href="ch11-03-test-organization.html"><strong aria-hidden="true">11.3.</strong> 🚧 L'organisation des tests</a></li></ol></li><li class="chapter-item expanded "><a href="ch12-00-an-io-project.html"><strong aria-hidden="true">12.</strong> 🚧 Un projet d'entrée/sortie : construire un programme en ligne de commande</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch12-01-accepting-command-line-arguments.html"><strong aria-hidden="true">12.1.</strong> 🚧 Récupérer les arguments de la ligne de commande</a></li><li class="chapter-item expanded "><a href="ch12-02-reading-a-file.html"><strong aria-hidden="true">12.2.</strong> 🚧 Lire un fichier</a></li><li class="chapter-item expanded "><a href="ch12-03-improving-error-handling-and-modularity.html"><strong aria-hidden="true">12.3.</strong> 🚧 Remanier le code pour améliorer sa modularité et la gestion des erreurs</a></li><li class="chapter-item expanded "><a href="ch12-04-testing-the-librarys-functionality.html"><strong aria-hidden="true">12.4.</strong> 🚧 Développer les fonctionnalités de la bibliothèque avec le TDD</a></li><li class="chapter-item expanded "><a href="ch12-05-working-with-environment-variables.html"><strong aria-hidden="true">12.5.</strong> 🚧 Travailler avec des variables d'environnement</a></li><li class="chapter-item expanded "><a href="ch12-06-writing-to-stderr-instead-of-stdout.html"><strong aria-hidden="true">12.6.</strong> 🚧 Ecrire les messages d'erreur sur la sortie d'erreurs standard au lieu de la sortie normale</a></li></ol></li><li class="chapter-item expanded "><a href="ch13-00-functional-features.html"><strong aria-hidden="true">13.</strong> Les fonctionnalités des langages fonctionnels : les itérateurs et les fermetures</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch13-01-closures.html"><strong aria-hidden="true">13.1.</strong> Les fermetures : fonctions anonymes qui peuvent utiliser leur environnement</a></li><li class="chapter-item expanded "><a href="ch13-02-iterators.html"><strong aria-hidden="true">13.2.</strong> Traiter une série d'éléments avec un itérateur</a></li><li class="chapter-item expanded "><a href="ch13-03-improving-our-io-project.html"><strong aria-hidden="true">13.3.</strong> Amélioration de notre projet d'entrée/sortie</a></li><li class="chapter-item expanded "><a href="ch13-04-performance.html"><strong aria-hidden="true">13.4.</strong> Comparaison des performances : les boucles et les itérateurs</a></li></ol></li><li class="chapter-item expanded "><a href="ch14-00-more-about-cargo.html"><strong aria-hidden="true">14.</strong> 🚧 En savoir plus sur cargo et crates.io</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch14-01-release-profiles.html"><strong aria-hidden="true">14.1.</strong> 🚧 Personnaliser les compilations avec les profils de publication</a></li><li class="chapter-item expanded "><a href="ch14-02-publishing-to-crates-io.html"><strong aria-hidden="true">14.2.</strong> 🚧 Publier une crate sur crates.io</a></li><li class="chapter-item expanded "><a href="ch14-03-cargo-workspaces.html"><strong aria-hidden="true">14.3.</strong> 🚧 Les espaces de travail de cargo</a></li><li class="chapter-item expanded "><a href="ch14-04-installing-binaries.html"><strong aria-hidden="true">14.4.</strong> 🚧 Installer des binaires à partir de crates.io avec cargo install</a></li><li class="chapter-item expanded "><a href="ch14-05-extending-cargo.html"><strong aria-hidden="true">14.5.</strong> 🚧 Etendre les fonctionnalités de cargo avec des commandes personnalisées</a></li></ol></li><li class="chapter-item expanded "><a href="ch15-00-smart-pointers.html"><strong aria-hidden="true">15.</strong> 🚧 Les pointeurs intelligents</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch15-01-box.html"><strong aria-hidden="true">15.1.</strong> 🚧 Utiliser Box<T> pour pointer sur des données présentes sur le tas</a></li><li class="chapter-item expanded "><a href="ch15-02-deref.html"><strong aria-hidden="true">15.2.</strong> 🚧 Considérer les pointeurs intelligents comme des références grâce au trait Deref</a></li><li class="chapter-item expanded "><a href="ch15-03-drop.html"><strong aria-hidden="true">15.3.</strong> 🚧 Exécuter du code au nettoyage avec le trait Drop</a></li><li class="chapter-item expanded "><a href="ch15-04-rc.html"><strong aria-hidden="true">15.4.</strong> 🚧 Rc<T>, le pointeur intelligent qui compte les références</a></li><li class="chapter-item expanded "><a href="ch15-05-interior-mutability.html"><strong aria-hidden="true">15.5.</strong> 🚧 RefCell<T> et le motif de mutabilité interne</a></li><li class="chapter-item expanded "><a href="ch15-06-reference-cycles.html"><strong aria-hidden="true">15.6.</strong> 🚧 Les boucles de références qui peuvent provoquer des fuites de mémoire</a></li></ol></li><li class="chapter-item expanded "><a href="ch16-00-concurrency.html"><strong aria-hidden="true">16.</strong> 🚧 La concurrence sans craintes</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch16-01-threads.html"><strong aria-hidden="true">16.1.</strong> 🚧 Utiliser les tâches pour exécuter simultanément du code</a></li><li class="chapter-item expanded "><a href="ch16-02-message-passing.html"><strong aria-hidden="true">16.2.</strong> 🚧 Utiliser l'envoi de messages pour transférer des données entre les tâches</a></li><li class="chapter-item expanded "><a href="ch16-03-shared-state.html"><strong aria-hidden="true">16.3.</strong> 🚧 Le partage d'état en concurrence</a></li><li class="chapter-item expanded "><a href="ch16-04-extensible-concurrency-sync-and-send.html"><strong aria-hidden="true">16.4.</strong> 🚧 Etendre la concurrence avec les traits Sync et Send</a></li></ol></li><li class="chapter-item expanded "><a href="ch17-00-oop.html"><strong aria-hidden="true">17.</strong> Les fonctionnalités orientées objet de Rust</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch17-01-what-is-oo.html"><strong aria-hidden="true">17.1.</strong> 🚧 Les caractéristiques des langages orientés objet</a></li><li class="chapter-item expanded "><a href="ch17-02-trait-objects.html"><strong aria-hidden="true">17.2.</strong> 🚧 Utiliser les objets traits qui permettent des valeurs de types différents</a></li><li class="chapter-item expanded "><a href="ch17-03-oo-design-patterns.html"><strong aria-hidden="true">17.3.</strong> 🚧 Implémenter un patron de conception orienté-objet</a></li></ol></li><li class="chapter-item expanded "><a href="ch18-00-patterns.html"><strong aria-hidden="true">18.</strong> 🚧 Les motifs et le filtrage par motif</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch18-01-all-the-places-for-patterns.html"><strong aria-hidden="true">18.1.</strong> 🚧 Tous les endroits où les motifs peuvent être utilisés</a></li><li class="chapter-item expanded "><a href="ch18-02-refutability.html"><strong aria-hidden="true">18.2.</strong> 🚧 La réfutabilité : lorsqu'un motif peut échouer à correspondre</a></li><li class="chapter-item expanded "><a href="ch18-03-pattern-syntax.html"><strong aria-hidden="true">18.3.</strong> 🚧 La syntaxe des motifs</a></li></ol></li><li class="chapter-item expanded "><a href="ch19-00-advanced-features.html"><strong aria-hidden="true">19.</strong> 🚧 Les fonctionnalités avancées</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch19-01-unsafe-rust.html"><strong aria-hidden="true">19.1.</strong> 🚧 Le Rust non sécurisé (unsafe)</a></li><li class="chapter-item expanded "><a href="ch19-03-advanced-traits.html"><strong aria-hidden="true">19.2.</strong> 🚧 Les traits avancés</a></li><li class="chapter-item expanded "><a href="ch19-04-advanced-types.html"><strong aria-hidden="true">19.3.</strong> 🚧 Les types avancés</a></li><li class="chapter-item expanded "><a href="ch19-05-advanced-functions-and-closures.html"><strong aria-hidden="true">19.4.</strong> 🚧 Les fonctions et fermetures avancées</a></li><li class="chapter-item expanded "><a href="ch19-06-macros.html"><strong aria-hidden="true">19.5.</strong> 🚧 Les macros</a></li></ol></li><li class="chapter-item expanded "><a href="ch20-00-final-project-a-web-server.html"><strong aria-hidden="true">20.</strong> 🚧 Projet final : construire un serveur web multitâches</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="ch20-01-single-threaded.html"><strong aria-hidden="true">20.1.</strong> 🚧 Développer un serveur web monotâche</a></li><li class="chapter-item expanded "><a href="ch20-02-multithreaded.html"><strong aria-hidden="true">20.2.</strong> 🚧 Transformer notre serveur monotâche en serveur multitâches</a></li><li class="chapter-item expanded "><a href="ch20-03-graceful-shutdown-and-cleanup.html"><strong aria-hidden="true">20.3.</strong> 🚧 Arrêt propre et nettoyage</a></li></ol></li><li class="chapter-item expanded "><a href="appendix-00.html"><strong aria-hidden="true">21.</strong> 🚧 Annexes</a></li><li><ol class="section"><li class="chapter-item expanded "><a href="appendix-01-keywords.html"><strong aria-hidden="true">21.1.</strong> 🚧 A - les mots-clés</a></li><li class="chapter-item expanded "><a href="appendix-02-operators.html"><strong aria-hidden="true">21.2.</strong> 🚧 B - les opérateurs et les symboles</a></li><li class="chapter-item expanded "><a href="appendix-03-derivable-traits.html"><strong aria-hidden="true">21.3.</strong> 🚧 C - les traits dérivables</a></li><li class="chapter-item expanded "><a href="appendix-04-useful-development-tools.html"><strong aria-hidden="true">21.4.</strong> 🚧 D - Des outils de développement utiles</a></li><li class="chapter-item expanded "><a href="appendix-05-editions.html"><strong aria-hidden="true">21.5.</strong> 🚧 E - Les éditions</a></li><li class="chapter-item expanded "><a href="appendix-06-translation.html"><strong aria-hidden="true">21.6.</strong> 🚧 F - Les traductions de ce livre</a></li><li class="chapter-item expanded "><a href="appendix-07-nightly-rust.html"><strong aria-hidden="true">21.7.</strong> 🚧 G - Comment Rust est construit, et “Nightly Rust”</a></li></ol></li></ol>
            </div>
            <div id="sidebar-resize-handle" class="sidebar-resize-handle"></div>
        </nav>

        <div id="page-wrapper" class="page-wrapper">

            <div class="page">
                
                <div id="menu-bar-hover-placeholder"></div>
                <div id="menu-bar" class="menu-bar sticky bordered">
                    <div class="left-buttons">
                        <button id="sidebar-toggle" class="icon-button" type="button" title="Toggle Table of Contents" aria-label="Toggle Table of Contents" aria-controls="sidebar">
                            <i class="fa fa-bars"></i>
                        </button>
                        <button id="theme-toggle" class="icon-button" type="button" title="Change theme" aria-label="Change theme" aria-haspopup="true" aria-expanded="false" aria-controls="theme-list">
                            <i class="fa fa-paint-brush"></i>
                        </button>
                        <ul id="theme-list" class="theme-popup" aria-label="Themes" role="menu">
                            <li role="none"><button role="menuitem" class="theme" id="light">Light (default)</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="rust">Rust</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="coal">Coal</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="navy">Navy</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="ayu">Ayu</button></li>
                        </ul>
                        
                        <button id="search-toggle" class="icon-button" type="button" title="Search. (Shortkey: s)" aria-label="Toggle Searchbar" aria-expanded="false" aria-keyshortcuts="S" aria-controls="searchbar">
                            <i class="fa fa-search"></i>
                        </button>
                        
                    </div>

                    <h1 class="menu-title">Le langage de programmation Rust</h1>

                    <div class="right-buttons">
                        
                        <a href="print.html" title="Print this book" aria-label="Print this book">
                            <i id="print-button" class="fa fa-print"></i>
                        </a>
                        
                        
                    </div>
                </div>

                
                <div id="search-wrapper" class="hidden">
                    <form id="searchbar-outer" class="searchbar-outer">
                        <input type="search" name="search" id="searchbar" name="searchbar" placeholder="Search this book ..." aria-controls="searchresults-outer" aria-describedby="searchresults-header">
                    </form>
                    <div id="searchresults-outer" class="searchresults-outer hidden">
                        <div id="searchresults-header" class="searchresults-header"></div>
                        <ul id="searchresults">
                        </ul>
                    </div>
                </div>
                

                <!-- Apply ARIA attributes after the sidebar and the sidebar toggle button are added to the DOM -->
                <script type="text/javascript">
                    document.getElementById('sidebar-toggle').setAttribute('aria-expanded', sidebar === 'visible');
                    document.getElementById('sidebar').setAttribute('aria-hidden', sidebar !== 'visible');
                    Array.from(document.querySelectorAll('#sidebar a')).forEach(function(link) {
                        link.setAttribute('tabIndex', sidebar === 'visible' ? 0 : -1);
                    });
                </script>

                <div id="content" class="content">
                    <main>
                        <!--
## Recoverable Errors with `Result`
-->
<h2><a class="header" href="#des-erreurs-récupérables-avec-result" id="des-erreurs-récupérables-avec-result">Des erreurs récupérables avec <code>Result</code></a></h2>
<!--
Most errors aren’t serious enough to require the program to stop entirely.
Sometimes, when a function fails, it’s for a reason that you can easily
interpret and respond to. For example, if you try to open a file and that
operation fails because the file doesn’t exist, you might want to create the
file instead of terminating the process.
-->
<p>La plupart des erreurs ne sont pas assez graves au point d'arrêter complètement
le programme. Parfois, lorsque une fonction échoue, c'est pour une raison que
vous pouvez facilement comprendre et pour laquelle agir en conséquence. Par exemple, si vous
essayez d'ouvrir un fichier et que l'opération échoue parce que le fichier
n'existe pas, vous pourriez vouloir créer le fichier plutôt que d'arrêter le
processus.</p>
<!--
Recall from [“Handling Potential Failure with the `Result`
Type”][handle_failure]<!-- ignore -- > in Chapter 2 that the `Result` enum is
defined as having two variants, `Ok` and `Err`, as follows:
-->
<p>Souvenez-vous de la section
<a href="ch02-00-guessing-game-tutorial.html#g%C3%A9rer-les-erreurs-potentielles-avec-le-type-result">“Gérer les erreurs potentielles avec le type <code>Result</code>”</a><!-- ignore -->
du chapitre 2 lorsque l'énumération <code>Result</code> pouvait avoir deux variantes, <code>Ok</code>
et <code>Err</code>, comme ci-dessous :</p>
<!--
[handle_failure]: ch02-00-guessing-game-tutorial.html#handling-potential-failure-with-the-result-type
-->
<!--
```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```
-->
<pre><pre class="playground"><code class="language-rust">
<span class="boring">#![allow(unused)]
</span><span class="boring">fn main() {
</span>enum Result&lt;T, E&gt; {
    Ok(T),
    Err(E),
}
<span class="boring">}
</span></code></pre></pre>
<!--
The `T` and `E` are generic type parameters: we’ll discuss generics in more
detail in Chapter 10. What you need to know right now is that `T` represents
the type of the value that will be returned in a success case within the `Ok`
variant, and `E` represents the type of the error that will be returned in a
failure case within the `Err` variant. Because `Result` has these generic type
parameters, we can use the `Result` type and the functions that the standard
library has defined on it in many different situations where the successful
value and error value we want to return may differ.
-->
<p>Le <code>T</code> et <code>E</code> sont des paramètres de type génériques : nous allons parler plus
en détail des génériques au chapitre 10. Tout ce que vous avez besoin de savoir
pour le moment, c'est que <code>T</code> représente le type de valeur imbriquée dans la
variante <code>Ok</code> qui sera retournée dans le cas d'un succès, et <code>E</code> représente le
type d'erreur imbriquée dans la variante <code>Err</code> qui sera retournée dans le cas
d'un échec. Comme <code>Result</code> a ces types de paramètres génériques, nous pouvons
utiliser le type <code>Result</code> et les fonctions que la bibliothèque standard qui lui
ont été associées pour différentes situations où la valeur de succès et la
valeur d'erreur peuvent être différentes.</p>
<!--
Let’s call a function that returns a `Result` value because the function could
fail. In Listing 9-3 we try to open a file.
-->
<p>Utilisons une fonction qui retourne une valeur de type <code>Result</code> car la fonction
peut échouer. Dans l'encart 9-3 nous essayons d'ouvrir un fichier :</p>
<!--
<span class="filename">Filename: src/main.rs</span>
-->
<p><span class="filename">Fichier : src/main.rs</span></p>
<!--
```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");
}
```
-->
<pre><pre class="playground"><code class="language-rust">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;);
}
</code></pre></pre>
<!--
<span class="caption">Listing 9-3: Opening a file</span>
-->
<p><span class="caption">Encart 9-3 : ouverture d'un fichier</span></p>
<!--
How do we know `File::open` returns a `Result`? We could look at the [standard
library API documentation](../std/index.html)<!-- ignore -- >, or we could ask
the compiler! If we give `f` a type annotation that we know is *not* the return
type of the function and then try to compile the code, the compiler will tell
us that the types don’t match. The error message will then tell us what the
type of `f` *is*. Let’s try it! We know that the return type of `File::open`
isn’t of type `u32`, so let’s change the `let f` statement to this:
-->
<p>Comment savons-nous que <code>File::open</code> retourne un <code>Result</code> ? Nous pouvons
regarder la
<a href="https://doc.rust-lang.org/std/index.html">documentation de l'API de la bibliothèque standard</a><!-- ignore -->,
ou nous pouvons demander au compilateur ! Si nous appliquons à <code>f</code> une
annotation de type dont nous savons qu'elle n'est <em>pas</em> le type de retour de la
fonction et que nous essayons ensuite de compiler le code, le compilateur va
nous dire que les types ne correspondent pas. Le message d'erreur va ensuite
nous dire <em>quel est le type</em> de <code>f</code>. Essayons cela ! Nous savons que le
retour de <code>File::open</code> n'est pas du type <code>u32</code>, alors essayons de changer
l'instruction <code>let f</code> par ceci :</p>
<!--
```rust,ignore,does_not_compile
# use std::fs::File;
# 
# fn main() {
    let f: u32 = File::open("hello.txt");
# }
```
-->
<pre><code class="language-rust ignore does_not_compile"><span class="boring">use std::fs::File;
</span><span class="boring">
</span><span class="boring">fn main() {
</span>    let f: u32 = File::open(&quot;hello.txt&quot;);
<span class="boring">}
</span></code></pre>
<!--
Attempting to compile now gives us the following output:
-->
<p>La compilation nous donne maintenant le résultat suivant :</p>
<!--
```console
$ cargo run
   Compiling error-handling v0.1.0 (file:///projects/error-handling)
error[E0308]: mismatched types
 -- > src/main.rs:4:18
  |
4 |     let f: u32 = File::open("hello.txt");
  |            ---   ^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found enum `std::result::Result`
  |            |
  |            expected due to this
  |
  = note: expected type `u32`
             found enum `std::result::Result<File, std::io::Error>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `error-handling`

To learn more, run the command again with --verbose.
```
-->
<pre><code class="language-console">$ cargo run
   Compiling error-handling v0.1.0 (file:///projects/error-handling)
error[E0308]: mismatched types
 --&gt; src/main.rs:4:18
  |
4 |     let f: u32 = File::open(&quot;hello.txt&quot;);
  |            ---   ^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found enum `std::result::Result`
  |            |
  |            expected due to this
  |
  = note: expected type `u32`
             found enum `std::result::Result&lt;File, std::io::Error&gt;`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `error-handling`

To learn more, run the command again with --verbose.
</code></pre>
<!--
This tells us the return type of the `File::open` function is a `Result<T, E>`.
The generic parameter `T` has been filled in here with the type of the success
value, `std::fs::File`, which is a file handle. The type of `E` used in the
error value is `std::io::Error`.
-->
<p>Cela nous dit que le retour de la fonction <code>File::open</code> est du type
<code>Result&lt;T, E&gt;</code>. Le paramètre générique <code>T</code> a été remplacé dans ce cas par le
type en cas de succès, <code>std::fs::File</code>, qui permet d'interagir avec le fichier.
Le <code>E</code> utilisé pour la valeur d'erreur est du type <code>std::io::Error</code>.</p>
<!--
This return type means the call to `File::open` might succeed and return a file
handle that we can read from or write to. The function call also might fail:
for example, the file might not exist, or we might not have permission to
access the file. The `File::open` function needs to have a way to tell us
whether it succeeded or failed and at the same time give us either the file
handle or error information. This information is exactly what the `Result` enum
conveys.
-->
<p>Ce type de retour veut dire que l'appel à <code>File::open</code> peut réussir et nous
retourner un manipulateur de fichier qui peut nous permettre de le lire ou
l'écrire. L'utilisation de cette fonction peut aussi échouer : par exemple, le
fichier peut ne pas exister, ou nous n'avons pas le droit d'accéder au fichier.
La fonction <code>File::open</code> doit avoir un moyen de nous dire si son utilisation a
réussi ou échoué et en même temps nous fournir soit le manipulateur de fichier
soit des informations sur l'erreur. C'est exactement ces informations que
l'énumération <code>Result</code> se charge de nous transmettre.</p>
<!--
In the case where `File::open` succeeds, the value in the variable `f` will be
an instance of `Ok` that contains a file handle. In the case where it fails,
the value in `f` will be an instance of `Err` that contains more information
about the kind of error that happened.
-->
<p>Dans le cas où <code>File::open</code> réussit, la valeur que nous obtenons dans la
variable <code>f</code> sera une instance de <code>Ok</code> qui contiendra un manipulateur de
fichier. Dans le cas où cela échoue, la valeur dans <code>f</code> sera une instance de
<code>Err</code> qui contiendra plus d'information sur le type d'erreur qui a eu lieu.</p>
<!--
We need to add to the code in Listing 9-3 to take different actions depending
on the value `File::open` returns. Listing 9-4 shows one way to handle the
`Result` using a basic tool, the `match` expression that we discussed in
Chapter 6.
-->
<p>Nous avons besoin d'ajouter différentes actions dans le code de l'encart 9-3 en
fonction de la valeur que <code>File::open</code> a retourné. L'encart 9-4 montre une façon
de gérer <code>Result</code> en utilisant un outil basique, l'expression <code>match</code> que nous
avons vu au chapitre 6.</p>
<!--
<span class="filename">Filename: src/main.rs</span>
-->
<p><span class="filename">Fichier : src/main.rs</span></p>
<!--
```rust,should_panic
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {:?}", error),
    };
}
```
-->
<pre><pre class="playground"><code class="language-rust should_panic">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;);

    let f = match f {
        Ok(fichier) =&gt; fichier,
        Err(erreur) =&gt; panic!(&quot;Erreur lors de l'ouverture du fichier : {:?}&quot;, erreur),
    };
}
</code></pre></pre>
<!--
<span class="caption">Listing 9-4: Using a `match` expression to handle the
`Result` variants that might be returned</span>
-->
<p><span class="caption">Encart 9-4: utilisation de l'expression <code>match</code> pour
gérer les variantes que <code>Result</code> pourrait retourner</span></p>
<!--
Note that, like the `Option` enum, the `Result` enum and its variants have been
brought into scope by the prelude, so we don’t need to specify `Result::`
before the `Ok` and `Err` variants in the `match` arms.
-->
<p>Remarquez que comme l'énumération <code>Option</code>, l'énumération <code>Result</code> et ses
variantes ont été importés par l'étape préliminaire, donc vous n'avez pas
besoin de préciser <code>Result::</code> devant les variantes <code>Ok</code> et <code>Err</code> dans les
branches du <code>match</code>.</p>
<!--
Here we tell Rust that when the result is `Ok`, return the inner `file` value
out of the `Ok` variant, and we then assign that file handle value to the
variable `f`. After the `match`, we can use the file handle for reading or
writing.
-->
<p>Ici nous indiquons à Rust que quand le résultat est <code>Ok</code>, il faut sortir la
valeur <code>fichier</code> de la variante <code>Ok</code>, et nous assignons ensuite cette valeur à
la variable <code>f</code>. Après le <code>match</code>, nous pourrons ensuite utiliser le
manipulateur de fichier pour lire ou écrire.</p>
<!--
The other arm of the `match` handles the case where we get an `Err` value from
`File::open`. In this example, we’ve chosen to call the `panic!` macro. If
there’s no file named *hello.txt* in our current directory and we run this
code, we’ll see the following output from the `panic!` macro:
-->
<p>L'autre branche du bloc <code>match</code> gère le cas où nous obtenons un <code>Err</code> à l'appel
de <code>File::open</code>. Dans cet exemple, nous avons choisi de faire appel à la macro
<code>panic!</code>. S'il n'y a pas de fichier qui s'appelle <em>hello.txt</em> dans notre
répertoire actuel et que nous exécutons ce code, nous allons voir la sortie
suivante suite à l'appel de la macro <code>panic!</code> :</p>
<!--
```text
$ cargo run
   Compiling error-handling v0.1.0 (file:///projects/error-handling)
    Finished dev [unoptimized + debuginfo] target(s) in 0.73s
     Running `target/debug/error-handling`
thread 'main' panicked at 'Problem opening the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:8:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
-->
<pre><code class="language-text">$ cargo run
   Compiling error-handling v0.1.0 (file:///projects/error-handling)
    Finished dev [unoptimized + debuginfo] target(s) in 0.73s
     Running `target/debug/error-handling`
thread 'main' panicked at 'Problem opening the file: Os { code: 2, kind: NotFound, message: &quot;No such file or directory&quot; }', src/main.rs:8:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</code></pre>
<!--
As usual, this output tells us exactly what has gone wrong.
-->
<p>Comme d'habitude, cette sortie nous explique avec précision ce qui s'est mal
passé.</p>
<!--
### Matching on Different Errors
-->
<h3><a class="header" href="#tester-les-différentes-erreurs" id="tester-les-différentes-erreurs">Tester les différentes erreurs</a></h3>
<!--
The code in Listing 9-4 will `panic!` no matter why `File::open` failed. What
we want to do instead is take different actions for different failure reasons:
if `File::open` failed because the file doesn’t exist, we want to create the
file and return the handle to the new file. If `File::open` failed for any
other reason—for example, because we didn’t have permission to open the file—we
still want the code to `panic!` in the same way as it did in Listing 9-4. Look
at Listing 9-5, which adds an inner `match` expression.
-->
<p>Le code dans l'encart 9-4 va faire un <code>panic!</code> peu importe la raison de l'échec
de <code>File::open</code>. Ce que nous voudrions plutôt faire est de réagir différemment en
fonction de différents cas d'erreurs : si <code>File::open</code> a échoué parce que le
fichier n'existe pas, nous voulons créer le fichier et renvoyer le manipulateur
de fichier pour ce nouveau fichier. Si <code>File::open</code> échoue pour toute autre
raison, par exemple si nous n'avons pas l'autorisation d'ouvrir le fichier,
nous voulons quand même que le code lance un <code>panic!</code> de la même manière qu'il
l'a fait dans l'encart 9-4. Dans l'encart 9-5, nous avons ajouté un nouveau cas
au bloc <code>match</code> :</p>
<!--
<span class="filename">Filename: src/main.rs</span>
-->
<p><span class="filename">Fichier : src/main.rs</span></p>
<!--
<!-- ignore this test because otherwise it creates hello.txt which causes other
tests to fail lol -- >
-->
<!--
```rust,ignore
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => {
                panic!("Problem opening the file: {:?}", other_error)
            }
        },
    };
}
```
-->
<pre><code class="language-rust ignore">use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open(&quot;hello.txt&quot;);

    let f = match f {
        Ok(fichier) =&gt; fichier,
        Err(erreur) =&gt; match erreur.kind() {
            ErrorKind::NotFound =&gt; match File::create(&quot;hello.txt&quot;) {
                Ok(fc) =&gt; fc,
                Err(e) =&gt; panic!(&quot;Erreur lors de la création du fichier : {:?}&quot;, e),
            },
            autre_erreur =&gt; panic!(&quot;Erreur lors de l'ouverture du fichier : {:?}&quot;, autre_erreur),
        },
    };
}
</code></pre>
<!--
<span class="caption">Listing 9-5: Handling different kinds of errors in
different ways</span>
-->
<p><span class="caption">Encart 9-5 : gestion des différents cas d'erreurs avec des
actions différentes.</span></p>
<!--
The type of the value that `File::open` returns inside the `Err` variant is
`io::Error`, which is a struct provided by the standard library. This struct
has a method `kind` that we can call to get an `io::ErrorKind` value. The enum
`io::ErrorKind` is provided by the standard library and has variants
representing the different kinds of errors that might result from an `io`
operation. The variant we want to use is `ErrorKind::NotFound`, which indicates
the file we’re trying to open doesn’t exist yet. So we match on `f`, but we
also have an inner match on `error.kind()`.
-->
<p>La valeur de retour de <code>File::open</code> logée dans la variante <code>Err</code> est de type
<code>io::Error</code>, qui est une structure fournie par la bibliothèque standard. Cette
structure a une méthode <code>kind</code> que nous pouvons utiliser pour obtenir un retour
de type <code>io::ErrorKind</code>. L'énumération <code>io::ErrorKind</code> est fournie elle aussi
par la bibliothèque standard qui embarque des variantes qui représentent
différents types d'erreurs qui pourraient résulter d'une opération provenant du
module <code>io</code>. La variante que nous voulons utiliser est <code>ErrorKind::NotFound</code>,
qui nous informe que le fichier que nous essayons d'ouvrir n'existe pas encore.
Donc nous utilisons <code>match</code> sur <code>f</code>, mais nous avons dans celle-ci une autre
<code>match</code> sur <code>erreur.kind()</code>.</p>
<!--
The condition we want to check in the inner match is whether the value returned
by `error.kind()` is the `NotFound` variant of the `ErrorKind` enum. If it is,
we try to create the file with `File::create`. However, because `File::create`
could also fail, we need a second arm in the inner `match` expression. When the
file can’t be created, a different error message is printed. The second arm of
the outer `match` stays the same, so the program panics on any error besides
the missing file error.
-->
<p>Nous souhaitons vérifier dans le <code>match</code> interne si la valeur de retour de
<code>error.kind()</code> est la variante <code>NotFound</code> de l'énumération <code>ErrorKind</code>. Si c'est
le cas, nous essayons de créer le fichier avec <code>File::create</code>. Cependant, comme
<code>File::create</code> peut aussi échouer, nous avons besoin d'une seconde branche dans
le <code>match</code> à l'intérieur. Lorsque le fichier ne peut pas être créé, un message
d'erreur différent est affiché. La seconde branche du <code>match</code> principal reste
inchangé, donc le programme panique lorsqu'on rencontre une autre erreur que
l'absence de fichier.</p>
<!--
That’s a lot of `match`! The `match` expression is very useful but also very
much a primitive. In Chapter 13, you’ll learn about closures; the `Result<T,
E>` type has many methods that accept a closure and are implemented using
`match` expressions. Using those methods will make your code more concise. A
more seasoned Rustacean might write this code instead of Listing 9-5:
-->
<p>Cela commence à faire beaucoup de <code>match</code> ! L'expression <code>match</code> est très utile
mais est aussi assez rudimentaire. Dans le chapitre 13, vous allez en apprendre plus
sur les fermetures ; le type <code>Result&lt;T, E&gt;</code> a de nombreuses méthodes qui
acceptent une fermeture et qui sont implémentés en utilisant des expressions
<code>match</code>. L'utilisation de ces méthodes vont rendre votre code plus concis. Un
Rustacé plus habitué écrira ce code plutôt que celui de l'encart 9-5 :</p>
<!--
```rust,ignore
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| {
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
}
```
-->
<pre><code class="language-rust ignore">use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open(&quot;hello.txt&quot;).unwrap_or_else(|erreur| {
        if erreur.kind() == ErrorKind::NotFound {
            File::create(&quot;hello.txt&quot;).unwrap_or_else(|erreur| {
                panic!(&quot;Erreur lors de la création du fichier : {:?}&quot;, erreur);
            })
        } else {
            panic!(&quot;Erreur lors de l'ouverture du fichier : {:?}&quot;, erreur);
        }
    });
}
</code></pre>
<!--
Although this code has the same behavior as Listing 9-5, it doesn’t contain any
`match` expressions and is cleaner to read. Come back to this example after
you’ve read Chapter 13, and look up the `unwrap_or_else` method in the standard
library documentation. Many more of these methods can clean up huge nested
`match` expressions when you’re dealing with errors.
-->
<p>Bien que ce code ait le même comportement que celui de l'encart 9-5, il ne
contient aucune expression <code>match</code> et est plus facile à lire. Revenez sur cet
exemple après avoir lu le chapitre 13, et renseignez-vous sur la méthode
<code>unwrap_or_else</code> dans la documentation de la bibliothèque standard. De
nombreuses méthodes de ce type peuvent clarifier de grosses expressions <code>match</code>
lorsque vous traitez les erreurs.</p>
<!--
### Shortcuts for Panic on Error: `unwrap` and `expect`
-->
<h3><a class="header" href="#raccourci-pour-faire-un-panic-lors-dune-erreur--unwrap-et-expect" id="raccourci-pour-faire-un-panic-lors-dune-erreur--unwrap-et-expect">Raccourci pour faire un Panic lors d'une erreur : <code>unwrap</code> et <code>expect</code></a></h3>
<!--
Using `match` works well enough, but it can be a bit verbose and doesn’t always
communicate intent well. The `Result<T, E>` type has many helper methods
defined on it to do various tasks. One of those methods, called `unwrap`, is a
shortcut method that is implemented just like the `match` expression we wrote in
Listing 9-4. If the `Result` value is the `Ok` variant, `unwrap` will return
the value inside the `Ok`. If the `Result` is the `Err` variant, `unwrap` will
call the `panic!` macro for us. Here is an example of `unwrap` in action:
-->
<p>L'utilisation de <code>match</code> fonctionne assez bien, mais elle peut être un peu
verbeuse et ne communique pas forcément bien son intention. Le type
<code>Result&lt;T, R&gt;</code> a de nombreuses méthodes qui lui ont été définies pour différents
cas. Une de ces méthodes, qui s'appelle <code>unwrap</code>, a été implémentée comme
l'expression <code>match</code> que nous avons écrit dans l'encart 9-4. Si la valeur de
<code>Result</code> est une variante de <code>Ok</code>, <code>unwrap</code> va retourner la valeur dans le
<code>Ok</code>. Si le <code>Result</code> est une variante de <code>Err</code>, <code>unwrap</code> va appeler la macro
<code>panic!</code> pour nous. Voici un exemple de <code>unwrap</code> à l'action :</p>
<!--
<span class="filename">Filename: src/main.rs</span>
-->
<p><span class="filename">Fichier : src/main.rs</span></p>
<!--
```rust,should_panic
use std::fs::File;

fn main() {
    let f = File::open("hello.txt").unwrap();
}
```
-->
<pre><pre class="playground"><code class="language-rust should_panic">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;).unwrap();
}
</code></pre></pre>
<!--
If we run this code without a *hello.txt* file, we’ll see an error message from
the `panic!` call that the `unwrap` method makes:
-->
<p>Si nous exécutons ce code sans le fichier <em>hello.txt</em>, nous allons voir un
message d'erreur suite à l'appel à <code>panic!</code> que la méthode <code>unwrap</code> a fait :</p>
<!--
```text
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
repr: Os { code: 2, message: "No such file or directory" } }',
src/libcore/result.rs:906:4
```
-->
<pre><code class="language-text">thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
repr: Os { code: 2, message: &quot;No such file or directory&quot; } }',
src/libcore/result.rs:906:4
</code></pre>
<!--
Another method, `expect`, which is similar to `unwrap`, lets us also choose the
`panic!` error message. Using `expect` instead of `unwrap` and providing good
error messages can convey your intent and make tracking down the source of a
panic easier. The syntax of `expect` looks like this:
-->
<p>L'autre méthode, <code>expect</code>, qui ressemble à <code>unwrap</code>, nous donne la possibilité
de définir le message d'erreur du <code>panic!</code>. Utiliser <code>expect</code> plutôt que
<code>unwrap</code> et lui fournir un bon message d'erreur permet de mieux exprimer le
problème et faciliter la recherche de la source d'erreur. La syntaxe de <code>expect</code>
est la suivante :</p>
<!--
<span class="filename">Filename: src/main.rs</span>
-->
<p><span class="filename">Fichier : src/main.rs</span></p>
<!--
```rust,should_panic
use std::fs::File;

fn main() {
    let f = File::open("hello.txt").expect("Failed to open hello.txt");
}
```
-->
<pre><pre class="playground"><code class="language-rust should_panic">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;).expect(&quot;Echec à l'ouverture de hello.txt&quot;);
}
</code></pre></pre>
<!--
We use `expect` in the same way as `unwrap`: to return the file handle or call
the `panic!` macro. The error message used by `expect` in its call to `panic!`
will be the parameter that we pass to `expect`, rather than the default
`panic!` message that `unwrap` uses. Here’s what it looks like:
-->
<p>Nous utilisons <code>expect</code> de la même manière que <code>unwrap</code> : pour retourner le
manipulateur de fichier ou appeler la macro <code>panic!</code>. Le message d'erreur
utilisé par <code>expect</code> lors de son appel au <code>panic!</code> sera le paramètre que nous
avons passé à <code>expect</code>, plutôt que le message par défaut de <code>panic!</code>
qu'utilise <code>unwrap</code>. Voici ce que cela donne :</p>
<!--
```text
thread 'main' panicked at 'Failed to open hello.txt: Error { repr: Os { code:
2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
```
-->
<pre><code class="language-text">thread 'main' panicked at 'Echec à l'ouverture de hello.txt: Error { repr: Os {
code: 2, message: &quot;No such file or directory&quot; } }', src/libcore/result.rs:906:4
</code></pre>
<!--
Because this error message starts with the text we specified, `Failed to open
hello.txt`, it will be easier to find where in the code this error message is
coming from. If we use `unwrap` in multiple places, it can take more time to
figure out exactly which `unwrap` is causing the panic because all `unwrap`
calls that panic print the same message.
-->
<p>Comme ce message d'erreur commence par le texte que nous avons précisé, <code>Echec à l'ouverture de hello.txt</code>, ce sera plus facile de trouver où se situe ce message
d'erreur dans le code. Si nous utilisons <code>unwrap</code> à plusieurs endroits, cela
peut prendre plus de temps de comprendre exactement quel <code>unwrap</code> a causé la
panique, car tous les appels aux <code>unwrap</code> vont afficher le même message.</p>
<!--
### Propagating Errors
-->
<h3><a class="header" href="#propager-les-erreurs" id="propager-les-erreurs">Propager les Erreurs</a></h3>
<!--
When you’re writing a function whose implementation calls something that might
fail, instead of handling the error within this function, you can return the
error to the calling code so that it can decide what to do. This is known as
*propagating* the error and gives more control to the calling code, where there
might be more information or logic that dictates how the error should be
handled than what you have available in the context of your code.
-->
<p>Lorsque vous écrivez une fonction dont l'implémentation utilise quelque chose
qui peut échouer, au lieu de gérer l'erreur dans cette fonction, vous pouvez
retourner cette erreur au code qui l'appelle pour qu'il décide quoi faire. C'est
ce que l'on appelle <em>propager</em> l'erreur et donne ainsi plus de contrôle au code
qui appelle la fonction, dans lequel il peut y avoir plus d'informations ou
d'instructions pour traiter l'erreur que dans le contexte de votre code.</p>
<!--
For example, Listing 9-6 shows a function that reads a username from a file. If
the file doesn’t exist or can’t be read, this function will return those errors
to the code that called this function.
-->
<p>Par exemple, l'encart 9-6 montre une fonction qui lit le nom d'utilisateur à
partir d'un fichier. Si ce fichier n'existe pas ou ne peut pas être lu, cette
fonction va retourner ces erreurs au code qui a appelé cette fonction.</p>
<!--
<span class="filename">Filename: src/main.rs</span>
-->
<p><span class="filename">Fichier : src/main.rs</span></p>
<!--
<!-- Deliberately not using rustdoc_include here; the `main` function in the
file panics. We do want to include it for reader experimentation purposes, but
don't want to include it for rustdoc testing purposes. -- >
-->
<!--
```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");

    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
```
-->
<pre><pre class="playground"><code class="language-rust">
<span class="boring">#![allow(unused)]
</span><span class="boring">fn main() {
</span>use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let f = File::open(&quot;hello.txt&quot;);

    let mut f = match f {
        Ok(file) =&gt; file,
        Err(e) =&gt; return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&amp;mut s) {
        Ok(_) =&gt; Ok(s),
        Err(e) =&gt; Err(e),
    }
}
<span class="boring">}
</span></code></pre></pre>
<!--
<span class="caption">Listing 9-6: A function that returns errors to the
calling code using `match`</span>
-->
<p><span class="caption">Encart 9-6 : une fonction qui retourne les erreurs au
code qui l'appelle en utilisant <code>match</code></span></p>
<!--
This function can be written in a much shorter way, but we’re going to start by
doing a lot of it manually in order to explore error handling; at the end,
we’ll show the shorter way. Let’s look at the return type of the function first:
`Result<String, io::Error>`. This means the function is returning a value of
the type `Result<T, E>` where the generic parameter `T` has been filled in
with the concrete type `String` and the generic type `E` has been filled in
with the concrete type `io::Error`. If this function succeeds without any
problems, the code that calls this function will receive an `Ok` value that
holds a `String`—the username that this function read from the file. If this
function encounters any problems, the code that calls this function will
receive an `Err` value that holds an instance of `io::Error` that contains
more information about what the problems were. We chose `io::Error` as the
return type of this function because that happens to be the type of the error
value returned from both of the operations we’re calling in this function’s
body that might fail: the `File::open` function and the `read_to_string`
method.
-->
<p>Cette fonction peut être écrite de façon plus concise, mais nous avons décidé de
commencer par faire un maximum de choses manuellement pour découvrir la gestion
d'erreurs ; mais à la fin, nous verrons comment raccourcir le code. Commençons par
regarder le type de retour de la fonction : <code>Result&lt;String, io::Error&gt;</code>. Cela
signifie que la fonction retourne une valeur de type <code>Result&lt;T, E&gt;</code> où le
paramètre générique <code>T</code> a été remplacé par le type <code>String</code> et le paramètre
générique <code>E</code> a été remplacé par le type <code>io::Error</code>. Si cette fonction réussit
avec succès, le code qui appelle cette fonction va obtenir une valeur <code>Ok</code> qui
contient un <code>String</code>, le nom d'utilisateur que cette fonction lit dans le
fichier. Si cette fonction rencontre un problème, le code qui appelle cette
fonction va obtenir une valeur <code>Err</code> qui contient une instance de <code>io::Error</code>
qui donne plus d'informations sur la raison du problème. Nous avons choisi
<code>io::Error</code> comme type de retour de cette fonction parce qu'il se trouve que
c'est le type d'erreur de retour pour toutes les opérations qui peuvent échouer
que l'on utilise dans le corps de cette fonction : la fonction <code>File::open</code> et
la méthode <code>read_to_string</code>.</p>
<!--
The body of the function starts by calling the `File::open` function. Then we
handle the `Result` value returned with a `match` similar to the `match` in
Listing 9-4, only instead of calling `panic!` in the `Err` case, we return
early from this function and pass the error value from `File::open` back to the
calling code as this function’s error value. If `File::open` succeeds, we store
the file handle in the variable `f` and continue.
-->
<p>Le corps de la fonction commence par appeler la fonction <code>File::open</code>. Ensuite,
nous gérons la valeur <code>Result</code> retourné, avec un <code>match</code> similaire au <code>match</code>
dans l'encart 9-4, mais, au lieu d'appeler <code>panic!</code> dans le cas de <code>Err</code>, nous
retournons prématurément le résultat de la fonction avec la valeur d'erreur de
<code>File::open</code> au code appelant avec la valeur d'erreur de cette fonction. Si
<code>File::open</code> réussit, nous enregistrons le manipulateur de fichier dans la
variable <code>f</code> et nous continuons.</p>
<!--
Then we create a new `String` in variable `s` and call the `read_to_string`
method on the file handle in `f` to read the contents of the file into `s`. The
`read_to_string` method also returns a `Result` because it might fail, even
though `File::open` succeeded. So we need another `match` to handle that
`Result`: if `read_to_string` succeeds, then our function has succeeded, and we
return the username from the file that’s now in `s` wrapped in an `Ok`. If
`read_to_string` fails, we return the error value in the same way that we
returned the error value in the `match` that handled the return value of
`File::open`. However, we don’t need to explicitly say `return`, because this
is the last expression in the function.
-->
<p>Ensuite, nous créons un nouveau <code>String</code> dans la variable <code>s</code> et nous appelons
la méthode <code>read_to_string</code> sur le manipulateur de fichier <code>f</code> pour extraire le
contenu du fichier dans <code>s</code>. La méthode <code>read_to_string</code> retourne aussi un
<code>Result</code> car elle peut échouer, même si <code>File::open</code> réussit. Nous avons donc
besoin d'un nouveau <code>match</code> pour gérer ce <code>Result</code> : si <code>read_to_string</code>
réussit, alors notre fonction a réussi, et nous retournons le nom d'utilisateur
présent dans le contenu du fichier qui est maintenant intégré dans un <code>Ok</code>,
lui-même stocké dans <code>s</code>. Si <code>read_to_string</code> échoue, nous retournons la valeur
d'erreur de la même façon que nous avons retourné la valeur d'erreur dans le
<code>match</code> qui gérait la valeur de retour de <code>File::open</code>. Cependant, nous n'avons
pas besoin d'écrire explicitement <code>return</code>, car c'est la dernière expression
de la fonction.</p>
<!--
The code that calls this code will then handle getting either an `Ok` value
that contains a username or an `Err` value that contains an `io::Error`. We
don’t know what the calling code will do with those values. If the calling code
gets an `Err` value, it could call `panic!` and crash the program, use a
default username, or look up the username from somewhere other than a file, for
example. We don’t have enough information on what the calling code is actually
trying to do, so we propagate all the success or error information upward for
it to handle appropriately.
-->
<p>Le code qui appelle ce code va devoir ensuite gérer les cas où il récupère une
valeur <code>Ok</code> qui contient un nom d'utilisateur, ou une valeur <code>Err</code> qui contient
une <code>io::Error</code>. Nous ne savons pas ce que va faire le code appelant avec ces
valeurs. Si le code appelant obtient une valeur <code>Err</code>, il peut appeler <code>panic!</code>
et faire planter le programme, utiliser un nom d'utilisateur par défaut, ou
chercher le nom d'utilisateur autre part que dans ce fichier, par exemple. Nous
n'avons pas assez d'informations sur ce que le code appelant a l'intention de
faire, donc nous remontons toutes les informations de succès ou d'erreur vers le
haut pour qu'elles soient gérées correctement.</p>
<!--
This pattern of propagating errors is so common in Rust that Rust provides the
question mark operator `?` to make this easier.
-->
<p>Cette façon de propager les erreurs est si courante en Rust que Rust fournit
l'opérateur du point d'interrogation <code>?</code> pour faciliter ceci.</p>
<!--
#### A Shortcut for Propagating Errors: the `?` Operator
-->
<h4><a class="header" href="#un-raccourci-pour-propager-les-erreurs--lopérateur-" id="un-raccourci-pour-propager-les-erreurs--lopérateur-">Un raccourci pour propager les erreurs : l'opérateur <code>?</code></a></h4>
<!--
Listing 9-7 shows an implementation of `read_username_from_file` that has the
same functionality as it had in Listing 9-6, but this implementation uses the
`?` operator.
-->
<p>L'encart 9-7 montre une implémentation de <code>read_username_from_file</code> qui a les
mêmes fonctionnalités qu'elle a dans l'encart 9-6, mais cette implémentation
utilise l'opérateur point d'interrogation :</p>
<!--
<span class="filename">Filename: src/main.rs</span>
-->
<p><span class="filename">Fichier : src/main.rs</span></p>
<!--
<!-- Deliberately not using rustdoc_include here; the `main` function in the
file panics. We do want to include it for reader experimentation purposes, but
don't want to include it for rustdoc testing purposes. -- >
-->
<!--
```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}
```
-->
<pre><pre class="playground"><code class="language-rust">
<span class="boring">#![allow(unused)]
</span><span class="boring">fn main() {
</span>use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let mut f = File::open(&quot;hello.txt&quot;)?;
    let mut s = String::new();
    f.read_to_string(&amp;mut s)?;
    Ok(s)
}
<span class="boring">}
</span></code></pre></pre>
<!--
<span class="caption">Listing 9-7: A function that returns errors to the
calling code using the `?` operator</span>
-->
<p><span class="caption">Encart 9-7 : une fonction qui retourne les erreurs au code
appelant en utilisant l'opérateur <code>?</code></span></p>
<!--
The `?` placed after a `Result` value is defined to work in almost the same way
as the `match` expressions we defined to handle the `Result` values in Listing
9-6. If the value of the `Result` is an `Ok`, the value inside the `Ok` will
get returned from this expression, and the program will continue. If the value
is an `Err`, the `Err` will be returned from the whole function as if we had
used the `return` keyword so the error value gets propagated to the calling
code.
-->
<p>Le <code>?</code> placé après une valeur <code>Result</code> est conçu pour fonctionner presque de la
même manière que les expressions <code>match</code> que nous avons défini pour gérer les
valeurs <code>Result</code> dans l'encart 9-6. Si la valeur du <code>Result</code> est un <code>Ok</code>, la
valeur dans le <code>Ok</code> sera retournée par cette expression et le programme
continuera. Si la valeur est une <code>Err</code>, la <code>Err</code> sera retournée par la fonction
comme si nous avions utilisé le mot-clé <code>return</code> afin que la valeur d'erreur
soit propagée au code appelant.</p>
<!--
There is a difference between what the `match` expression from Listing 9-6 does
and what the `?` operator does: error values that have the `?` operator called
on them go through the `from` function, defined in the `From` trait in the
standard library, which is used to convert errors from one type into another.
When the `?` operator calls the `from` function, the error type received is
converted into the error type defined in the return type of the current
function. This is useful when a function returns one error type to represent all
the ways a function might fail, even if parts might fail for many different
reasons. As long as each error type implements the `from` function to define how
to convert itself to the returned error type, the `?` operator takes care of the
conversion automatically.
-->
<p>Il y a une différence entre ce que fait l'expression <code>match</code> de l'encart 9-6 et
ce que fait l'opérateur <code>?</code> : les valeurs d'erreurs sur lesquelles sont
utilisées l'opérateur <code>?</code> passent par la fonction <code>from</code>, définie dans le trait
<code>From</code> de la bibliothèque standard, qui est utilisée pour convertir les erreurs
d'un type à un autre. Lorsque l'opérateur <code>?</code> utilise la fonction <code>from</code>, le
type d'erreur reçu est converti dans le type d'erreur déclaré dans le type de
retour de la fonction concernée. C'est utile lorsque une fonction retourne un
type d'erreur qui peut couvrir tous les cas d'échec de la fonction, même si
certaines de ses parties peuvent échouer pour différentes raisons. A partir du
moment que chaque type d'erreur implémente la fonction <code>from</code> pour expliquer
comment se convertir elle-même dans le type d'erreur retourné, l'opérateur <code>?</code>
se charge de faire la conversion automatiquement.</p>
<!--
In the context of Listing 9-7, the `?` at the end of the `File::open` call will
return the value inside an `Ok` to the variable `f`. If an error occurs, the
`?` operator will return early out of the whole function and give any `Err`
value to the calling code. The same thing applies to the `?` at the end of the
`read_to_string` call.
-->
<p>Dans le cas de l'encart 9-7, le <code>?</code> à la fin de l'appel à <code>File::open</code> va
retourner la valeur à l'intérieur d'un <code>Ok</code> à la variable <code>f</code>. Si une erreur se
produit, l'opérateur <code>?</code> va retourner prématurément la fonction et fournir une
valeur <code>Err</code> au code appelant. La même chose se produira au <code>?</code> à ma fin de
l'appel à <code>read_to_string</code>.</p>
<!--
The `?` operator eliminates a lot of boilerplate and makes this function’s
implementation simpler. We could even shorten this code further by chaining
method calls immediately after the `?`, as shown in Listing 9-8.
-->
<p>L'opérateur <code>?</code> épargne de l'écriture de code et facilite l'implémentation de la
fonction. Nous pouvons même encore plus réduire ce code en enchaînant
immédiatement les appels aux méthodes après le <code>?</code> comme dans l'encart 9-8 :</p>
<!--
<span class="filename">Filename: src/main.rs</span>
-->
<p><span class="filename">Fichier : src/main.rs</span></p>
<!--
<!-- Deliberately not using rustdoc_include here; the `main` function in the
file panics. We do want to include it for reader experimentation purposes, but
don't want to include it for rustdoc testing purposes. -- >
-->
<!--
```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();

    File::open("hello.txt")?.read_to_string(&mut s)?;

    Ok(s)
}
```
-->
<pre><pre class="playground"><code class="language-rust">
<span class="boring">#![allow(unused)]
</span><span class="boring">fn main() {
</span>use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let mut s = String::new();

    File::open(&quot;hello.txt&quot;)?.read_to_string(&amp;mut s)?;

    Ok(s)
}
<span class="boring">}
</span></code></pre></pre>
<!--
<span class="caption">Listing 9-8: Chaining method calls after the `?`
operator</span>
-->
<p><span class="caption">Encart 9-8 : enchaînement des appels aux méthodes après
l'opérateur <code>?</code></span></p>
<!--
We’ve moved the creation of the new `String` in `s` to the beginning of the
function; that part hasn’t changed. Instead of creating a variable `f`, we’ve
chained the call to `read_to_string` directly onto the result of
`File::open("hello.txt")?`. We still have a `?` at the end of the
`read_to_string` call, and we still return an `Ok` value containing the
username in `s` when both `File::open` and `read_to_string` succeed rather than
returning errors. The functionality is again the same as in Listing 9-6 and
Listing 9-7; this is just a different, more ergonomic way to write it.
-->
<p>Nous avons déplacé la création de la nouvelle <code>String</code> dans <code>s</code> au début de la
fonction ; cette partie n'a pas changée. Au lieu de créer la variable <code>f</code>, nous
enchaînons directement l'appel à <code>read_to_string</code> sur le résultat de
<code>File::open(&quot;hello.txt&quot;)?</code>. Nous avons toujours le <code>?</code> à la fin de l'appel à
<code>read_to_string</code>, et nous retournons toujours une valeur <code>Ok</code> contenant le nom
d'utilisateur dans <code>s</code> lorsque <code>File::open</code> et <code>read_to_string</code> réussissent
toutes les deux plutôt que de retourner des erreurs. Cette fonctionnalité est
toujours la même que dans l'encart 9-6 et l'encart 9-7 ; c'est juste une façon
différente et plus ergonomique de l'écrire.</p>
<!--
Speaking of different ways to write this function, Listing 9-9 shows that
there’s a way to make this even shorter.
-->
<p>En parlant de différentes façons d'écrire cette fonction, l'encart 9-9 nous
montre qu'il y a une façon d'écrire encore moins de code.</p>
<!--
<span class="filename">Filename: src/main.rs</span>
-->
<p><span class="filename">Fichier : src/main.rs</span></p>
<!--
<!-- Deliberately not using rustdoc_include here; the `main` function in the
file panics. We do want to include it for reader experimentation purposes, but
don't want to include it for rustdoc testing purposes. -- >
-->
<!--
```rust
use std::fs;
use std::io;

fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```
-->
<pre><pre class="playground"><code class="language-rust">
<span class="boring">#![allow(unused)]
</span><span class="boring">fn main() {
</span>use std::fs;
use std::io;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    fs::read_to_string(&quot;hello.txt&quot;)
}
<span class="boring">}
</span></code></pre></pre>
<!--
<span class="caption">Listing 9-9: Using `fs::read_to_string` instead of
opening and then reading the file</span>
-->
<p><span class="caption">Encart 9-9: utilisation de <code>fs::read_to_string</code> plutôt que
d'ouvrir puis lire le fichier</span></p>
<!--
Reading a file into a string is a fairly common operation, so Rust provides the
convenient `fs::read_to_string` function that opens the file, creates a new
`String`, reads the contents of the file, puts the contents into that `String`,
and returns it. Of course, using `fs::read_to_string` doesn’t give us the
opportunity to explain all the error handling, so we did it the longer way
first.
-->
<p>Récupérer le contenu d'un fichier dans une <code>String</code> est une opération assez
courante, donc Rust fournir la fonction <code>fs::read_to_string</code> assez pratique, qui
ouvre le fichier, crée une nouvelle <code>String</code>, lit de contenu du fichier, envoie
le contenu dans cette <code>String</code>, et la retourne. Evidemment, l'utilisation de
<code>fs:read_to_string</code> ne nous offre pas l'occasion d'expliquer toute la gestion
des erreurs, donc nous utiliserons d'abord la façon qui est plus longue.</p>
<!--
#### The `?` Operator Can Be Used in Functions That Return `Result`
-->
<h4><a class="header" href="#lopérateur--peut-être-utilisé-dans-des-fonctions-qui-retournent-un-result" id="lopérateur--peut-être-utilisé-dans-des-fonctions-qui-retournent-un-result">L'opérateur <code>?</code> peut être utilisé dans des fonctions qui retournent un <code>Result</code></a></h4>
<!--
The `?` operator can be used in functions that have a return type of
`Result`, because it is defined to work in the same way as the `match`
expression we defined in Listing 9-6. The part of the `match` that requires a
return type of `Result` is `return Err(e)`, so the return type of the function
has to be a `Result` to be compatible with this `return`.
-->
<p>L'opérateur <code>?</code> peut être utilisé dans des fonctions qui ont un type de retour
<code>Result</code>, car il est conçu pour fonctionner de la même manière que l'expression
<code>match</code> que nous avons utilisé dans l'encart 9-6. La partie du <code>match</code> qui
nécessite le type de retour <code>Result</code> est <code>return Err(e)</code>, donc le type de retour
de cette fonction doit être un <code>Result</code> pour être compatible avec ce <code>return</code>.</p>
<!--
Let’s look at what happens if we use the `?` operator in the `main` function,
which you’ll recall has a return type of `()`:
-->
<p>Voyons ce que ce passe si nous utilisons l'opérateur <code>?</code> dans la fonction
<code>main</code>, pour laquelle vous devriez vous souvenir qu'elle a un type de retour
<code>()</code> :</p>
<!--
```rust,ignore,does_not_compile
use std::fs::File;

fn main() {
    let f = File::open("hello.txt")?;
}
```
-->
<pre><code class="language-rust ignore does_not_compile">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;)?;
}
</code></pre>
<!--
When we compile this code, we get the following error message:
-->
<p>Lorsque nous compilons ce code, nous obtenons le message d'erreur suivant :</p>
<!--
```console
$ cargo run
   Compiling error-handling v0.1.0 (file:///projects/error-handling)
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
 -- > src/main.rs:4:13
  |
3 | / fn main() {
4 | |     let f = File::open("hello.txt")?;
  | |             ^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
5 | | }
  | |_- this function should return `Result` or `Option` to accept `?`
  |
  = help: the trait `Try` is not implemented for `()`
  = note: required by `from_error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `error-handling`

To learn more, run the command again with --verbose.
```
-->
<pre><code class="language-console">$ cargo run
   Compiling error-handling v0.1.0 (file:///projects/error-handling)
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
 --&gt; src/main.rs:4:13
  |
3 | / fn main() {
4 | |     let f = File::open(&quot;hello.txt&quot;)?;
  | |             ^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
5 | | }
  | |_- this function should return `Result` or `Option` to accept `?`
  |
  = help: the trait `Try` is not implemented for `()`
  = note: required by `from_error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `error-handling`

To learn more, run the command again with --verbose.
</code></pre>
<!--
This error points out that we’re only allowed to use the `?` operator in a
function that returns `Result` or `Option` or another type that implements
`std::ops::Try`. When you’re writing code in a function
that doesn’t return one of these types, and you want to use `?` when you call other
functions that return `Result<T, E>`, you have two choices to fix this problem.
One technique is to change the return type of your function to be `Result<T,
E>` if you have no restrictions preventing that. The other technique is to use
a `match` or one of the `Result<T, E>` methods to handle the `Result<T, E>` in
whatever way is appropriate.
-->
<p>Cette erreur explique que nous sommes uniquement autorisés à utiliser
l'opérateur <code>?</code> dans une fonction qui retourne <code>Result</code> ou <code>Option</code> ou un autre
type qui implémente <code>std::ops::Try</code>. Lorsque vous écrivez du code dans une
fonction qui ne retourne pas un de ces types, et que vous souhaitez utiliser <code>?</code>
lorsque vous appelez d'autres fonctions qui retournent <code>Result&lt;T, E&gt;</code>, vous avez
deux façons de régler le problème. La première est de changer le type de retour
de votre fonction en <code>Result&lt;T, E&gt;</code> si vous pouvez le faire. L'autre solution
est d'utiliser un <code>match</code> ou une des méthodes de <code>Result&lt;T, E&gt;</code> pour gérer le
<code>Result&lt;T, E&gt;</code> de la manière la plus appropriée.</p>
<!--
The `main` function is special, and there are restrictions on what its return
type must be. One valid return type for main is `()`, and conveniently, another
valid return type is `Result<T, E>`, as shown here:
-->
<p>La fonction <code>main</code> est spéciale, et il y a des restrictions sur ce que doit être
son type de retour. Une type de retour correct pour <code>main</code> est <code>()</code>, et il
existe aussi un autre type de retour acceptable qui est <code>Result&lt;T, E&gt;</code>, comme
ci-dessous :</p>
<!--
```rust,ignore
use std::error::Error;
use std::fs::File;

fn main() -> Result<(), Box<dyn Error>> {
    let f = File::open("hello.txt")?;

    Ok(())
}
```
-->
<pre><code class="language-rust ignore">use std::error::Error;
use std::fs::File;

fn main() -&gt; Result&lt;(), Box&lt;dyn Error&gt;&gt; {
    let f = File::open(&quot;hello.txt&quot;)?;

    Ok(())
}
</code></pre>
<!--
The `Box<dyn Error>` type is called a trait object, which we’ll talk about in
the [“Using Trait Objects that Allow for Values of Different
Types”][trait-objects]<!-- ignore -- > section in Chapter 17. For now, you can
read `Box<dyn Error>` to mean “any kind of error.” Using `?` in a `main`
function with this return type is allowed.
-->
<p>Le type <code>Box&lt;dyn Error&gt;</code> est ce qu'on appelle un objet trait, que nous allons
voir dans une section du <a href="ch17-02-trait-objects.html">chapitre 17</a><!-- ignore -->. Pour
l'instant vous pouvez interpréter <code>Box&lt;dyn Error&gt;</code> en “tout type d'erreur”.
L'utilisation de <code>?</code> dans la fonction <code>main</code> avec ce type de retour est donc
autorisée.</p>
<!--
Now that we’ve discussed the details of calling `panic!` or returning `Result`,
let’s return to the topic of how to decide which is appropriate to use in which
cases.
-->
<p>Maintenant que nous avons vu les détails pour utiliser <code>panic!</code> ou retourner
<code>Result</code>, voyons maintenant comment choisir ce qu'il faut faire en fonction des
cas.</p>
<!--
[trait-objects]: ch17-02-trait-objects.html#using-trait-objects-that-allow-for-values-of-different-types
-->

                    </main>

                    <nav class="nav-wrapper" aria-label="Page navigation">
                        <!-- Mobile navigation buttons -->
                        
                            <a rel="prev" href="ch09-01-unrecoverable-errors-with-panic.html" class="mobile-nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                                <i class="fa fa-angle-left"></i>
                            </a>
                        

                        
                            <a rel="next" href="ch09-03-to-panic-or-not-to-panic.html" class="mobile-nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        

                        <div style="clear: both"></div>
                    </nav>
                </div>
            </div>

            <nav class="nav-wide-wrapper" aria-label="Page navigation">
                
                    <a rel="prev" href="ch09-01-unrecoverable-errors-with-panic.html" class="nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                        <i class="fa fa-angle-left"></i>
                    </a>
                

                
                    <a rel="next" href="ch09-03-to-panic-or-not-to-panic.html" class="nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                        <i class="fa fa-angle-right"></i>
                    </a>
                
            </nav>

        </div>

        

        

        

        
        <script type="text/javascript">
            window.playground_copyable = true;
        </script>
        

        

        
        <script src="elasticlunr.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="mark.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="searcher.js" type="text/javascript" charset="utf-8"></script>
        

        <script src="clipboard.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="highlight.js" type="text/javascript" charset="utf-8"></script>
        <script src="book.js" type="text/javascript" charset="utf-8"></script>

        <!-- Custom JS scripts -->
        
        <script type="text/javascript" src="../ferris.js"></script>
        
        <script type="text/javascript" src="github-button.js"></script>
        

        

    </body>
</html>
